/*
 * PROJECT:     SupernovaX SDK
 * LICENSE:     MIT (https://spdx.org/licenses/MIT)
 * PURPOSE:     Use reference COM interfaces
 * COPYRIGHT:   Copyright 2023 Christian Rendina <pizzaiolo100@proton.me>
 */
import "oaidl.idl";
import "ocidl.idl";

[
	object,
	local,
	uuid(ffffffff-ffff-ffff-ffff-ffffffffffff) // TODO: THIS IS AN INVALID UUID
]
interface IUseCounted : IUnknown
{
	ULONG UCAddUse(
		void
	);

	ULONG UCReleaseUse(
		void
	);

	HRESULT UCBreakCyclicReferences(
		void
	);

	HRESULT UCEnstablishCyclicReferences(
		void
	);

	HRESULT UCDestroy(
		void
	);
};

[
	object,
	local,
	uuid(9b7e4a04-342c-4106-a19f-4f2704f689f0)
]
interface IUseCounted2 : IUseCounted
{
	HRESULT UCQueryInterface(
		[in] UINT flags,
		[in] REFIID riid,
		[out] void** ppObj
	);
};
