target("dxtex")
    add_rules("win.sdk.mfc.shared_app")
    add_files("*.cpp")
    add_files("*.rc")
    add_headerfiles("*.h")
    set_pcxxheader("StdAfx.h")
    add_deps("dxguid")
    --add_links("d3d9", "d3dx9d")
    add_links("d3d9", "d3dx9")
    add_links("version")
    add_linkdirs("../../temp")