/*
 * PROJECT:     SupernovaX SDK
 * LICENSE:     MIT (https://spdx.org/licenses/MIT)
 * PURPOSE:     D3D10 Misc interface
 * COPYRIGHT:   Copyright 2024 Christian Rendina <pizzaiolo100@proton.me>
 * REFERENCE:
 * - Wine d3d10misc.h
 */
import "oaidl.idl";
import "ocidl.idl";

typedef enum D3D10_DRIVER_TYPE {
    D3D10_DRIVER_TYPE_HARDWARE  = 0,
    D3D10_DRIVER_TYPE_REFERENCE = 1,
    D3D10_DRIVER_TYPE_NULL      = 2,
    D3D10_DRIVER_TYPE_SOFTWARE  = 3,
    D3D10_DRIVER_TYPE_WARP      = 5,
} D3D10_DRIVER_TYPE;

cpp_quote("HRESULT WINAPI D3D10CreateDevice(IDXGIAdapter *adapter, D3D10_DRIVER_TYPE driver_type,")
cpp_quote("        HMODULE swrast, UINT flags, UINT sdk_version, ID3D10Device **device);")

cpp_quote("HRESULT WINAPI D3D10CreateDeviceAndSwapChain(IDXGIAdapter *adapter, D3D10_DRIVER_TYPE driver_type,")
cpp_quote("        HMODULE swrast, UINT flags, UINT sdk_version, DXGI_SWAP_CHAIN_DESC *swapchain_desc,")
cpp_quote("        IDXGISwapChain **swapchain, ID3D10Device **device);")

cpp_quote("HRESULT WINAPI D3D10CreateBlob(SIZE_T data_size, ID3D10Blob **blob);")
