/*
 * PROJECT:     ReactX
 * LICENSE:     MIT (https://spdx.org/licenses/MIT)
 * PURPOSE:     ReactX Direct Composition COM interfaces
 * COPYRIGHT:   Copyright 2023 Christian Rendina <pizzaiolo100@proton.me>
 */
import "oaidl.idl";
import "ocidl.idl";
import "dxgi.idl";

#ifndef _WIN7_SDK
import "dxgi1_2.idl";
#endif


[
	object,
	local,
	uuid(ffffffff-ffff-ffff-ffff-ffffffffffeb) // TODO: this UUID is invalid
]
interface IDXGIAdapterPartner : IUnknown
{
	HRESULT GetAdapterRole(

	);
};

#ifndef _WIN7_SDK
[
	object,
	local,
	uuid(7652c85a-0df5-4567-bcdd-8176a332b99b)
]
interface IDXGISwapChainPartner : IDXGIDeviceSubObject
{
	HRESULT GetCompositionInterface(
		[out] void** pInterface
	);
	
	HRESULT SetAlphaMode(
		[in] DXGI_ALPHA_MODE alphaMode
	);
};

[
	object,
	local,
	uuid(e17312b5-f3e7-4c72-9c67-74ddbfdd633c)
]
interface IDXGIFactoryPartner : IDXGIObject
{
	HRESULT CreateSwapChainForCompositionSurface(
		[in] IUnknown* pDevice,
		void*,
		[in] const DXGI_SWAP_CHAIN_DESC1* pSwapChainDesc1,
		[in] IDXGIOutput* pOutput,
		[out] IDXGISwapChain1** ppSwapChain1
	);
};
#endif
