@ cdecl __wine_dbg_get_channel_flags(ptr)
@ cdecl __wine_dbg_strdup(ptr)
@ cdecl __wine_dbg_output(ptr)
@ cdecl __wine_dbg_header(long ptr ptr)
@ varargs DbgPrint(long)
@ stdcall RtlRaiseException(ptr)
