@ stdcall -stub AcquireDDThreadLock()
@ stdcall -stub CheckFullscreen()
@ stdcall -stub CompleteCreateSysmemSurface()
@ stdcall -stub D3DParseUnknownCommand()
@ stdcall -stub DDGetAttachedSurfaceLcl()
@ stdcall -stub DDInternalLock()
@ stdcall -stub DDInternalUnlock()
@ stdcall -stub DSoundHelp()
@ stdcall DirectDrawCreate(ptr ptr ptr)
@ stdcall DirectDrawCreateClipper(long ptr ptr)
@ stdcall DirectDrawCreateEx(ptr ptr ptr ptr)
@ stdcall DirectDrawEnumerateA(ptr ptr)
@ stdcall DirectDrawEnumerateExA(ptr ptr long)
@ stdcall DirectDrawEnumerateW(ptr ptr)
@ stdcall DirectDrawEnumerateExW(ptr ptr long)
@ stdcall -private DllCanUnloadNow()
@ stdcall -private DllGetClassObject(ptr ptr ptr)
@ stdcall -stub GetDDSurfaceLocal()
@ stdcall -stub GetOLEThunkData()
@ stdcall -stub GetSurfaceFromDC()
@ stdcall -stub RegisterSpecialCase()
@ stdcall -stub ReleaseDDThreadLock()
