/*
 * PROJECT:     ReactX Graphics Infrastructure
 * COPYRIGHT:   See COPYING in the top level directory
 * PURPOSE:     DXGI Direct Composition
 * COPYRIGHT:   Copyright 2023 Christian Rendina <christian.rendina@gmail.com>
 */
import "oaidl.idl";
import "ocidl.idl";
import "dxgi.idl";

[
	object,
	local,
	uuid(ffffffff-ffff-ffff-ffff-ffffffffffeb) // TODO: this UUID is invalid
]
interface IDXGIAdapterPartner : IUnknown
{
	HRESULT GetAdapterRole(

	);
};

[
	object,
	local,
	uuid(ffffffff-ffff-ffff-ffff-fffffffffffa) // TODO: this UUID is invalid
]
interface IDXGISwapChainPartner : IDXGIDeviceSubObject
{
	HRESULT GetCompositionInterface(
	
	);
	
	HRESULT SetAlphaMode(
	
	);
	
	HRESULT GetFrameStatisticsPartner(
	
	);
	
	HRESULT GetLogicalSurfaceHandle(
	
	);
};

[
	object,
	local,
	uuid(ffffffff-ffff-ffff-ffff-ffffffffffc3) // TODO: this UUID is invalid
]
interface IDXGIFactoryPartner : IDXGIObject
{
	HRESULT CreateSwapChainForCompositionSurface(
		[in] IUnknown* pDevice,
		void*,
		[in] DXGI_SWAP_CHAIN_DESC1 pSwapChainDesc1,
		[in] IDXGIOutput* pOutput,
		[out] IDXGISwapChain1** ppSwapChain1
	);
};
